### ISSUE TITLE
More robust error handling

### ISSUE THREAD

**Issue by repr-man** [DDunda/SDL-plus-plus#5]
In the regular C API, errors must be handled for each SDL object created as follows:
```cpp
auto bmp = SDL_CreateRGBSurfaceWithFormatFrom("/incorrect/path", width, height, SDL_BITSPERPIXEL(format), pitch, format)
if(bmp->surface == nullptr)
{
    // Handle error...
    std::terminate();
}
```
This is clunky and awful.  With SDL++, we can do something like this:
```cpp
auto bmp = Surface("/incorrect/path");
if(bmp.surface == nullptr)
{
    // Handle error...
    std::terminate();
}
```
The error handling mechanism is fundamentally the same; we use an `if` statement to test if the pointer is null and handle it from there.

We can do better.

The first solution I propose would involve adding an error handling method to each object:
```cpp
auto&& handle(std::function<void()> fn = [](){})
{
	if(this->surface == nullptr)
	{
		fn();
	}
	return std::move(*this);
}
```
Objects would be constructed like this:
```cpp
auto bmp = Surface("/incorrect/path").handle([](){ std::terminate(); });
```
The downside is that this would require defining a move constructor for each object.  However, it might be useful for future additions and optimizations.  It could also be easily expanded with other types of error handling functions, (e.g. user-defined default values, etc.).

Another idea is to add a static creation method which forwards the arguments to the constructor and takes an additional argument with the user-defined error handling lambda:
```cpp
static Surface create(std::string file, std::function<void()> fn = [](){})
{
	auto tmp = Surface(file);
	if(tmp.surface == nullptr)
	{
		fn();
	}
	return tmp;
}
```
Objects would be constructed like this:
```cpp
auto bmp = Surface::create("/incorrect/path", [](){ std::terminate(); } );
```
The downside of this is that it deviates from the original SDL prototypes and could get to be a bit long.  It also could make method chaining a little difficult.  However, having a `create` function analogues original SDL and may be helpful for newcomers.  I checked the assembly, and it produces fewer calls than the other method because of copy elision and needing to call fewer constructors and destructors for temporary objects.

With either of these systems, the handling functions could be customized for each object so that only the pointers that need to be checked are checked, and that the default error handling is appropriate.  The user is also able to define a custom function in their own code and pass it in by pointer.
The existing constructors could either be made private to enforce error handling or be left alone to allow some users to skip checking for their _blazing fast_ code.

Implementing these for the entire library would be a massive undertaking, so naturally, I would be willing to do it on my own time and make a single pull request when I'm done.

If any of this sounds interesting or useful to you, or if you have better ideas, please let me know.

**Comment by DDunda** [comment]
Hi again, thanks for the proposal! Error checking is a pretty big problem, I agree, and I think something like this could work. I would suggest some modifications, however.

I don't think it's possible to have a single handle function, as objects can fail under many conditions, in ways that shouldn't necessarily invalidate their pointer, and with a very wide range of significance; A failed draw call vs a failed constructor carry very different implications, for example. I'm also not keen on moving objects every time they are checked, as it seems unnecessary.

I like the idea of improving error-checking, I would just prefer it be handled per-function. Maybe every function could have two overloads; one with no checking, and one with error-checking, (distinguished with a callback argument). There's also the possibility that traditional error throwing could work. The user could use try-catch blocks rather than callbacks, but this can be verbose. 

I feel this would allow a lot of flexibility with error severity levels and recovery, and would keep object data distinguished from errors. Under this type of error-checking, some code snippets may look like this:
```cpp
// Kill program if rendering screen fails
r.Present([]{std::terminate();});
```
```cpp
// Use a default texture if a texture could not be loaded
auto txt = IMG::LoadTexture(r, "/incorrect/path", [&](Texture& txt){txt = Texture(default_txt);});
```
or this:
```cpp
try {
	r.Present();
} catch {
	std::terminate();
}
```
```cpp
Texture txt;
try
	txt = IMG::LoadTexture(r, "/incorrect/path");
catch(...) {
	txt = Texture(default_txt);
}
```

Let me know what you think, thanks!

**Comment by repr-man** [comment]
Sorry for not getting back to you sooner.

I think I need a little more information about what you envision this library looking like before I make a full response.  Specifically, what would you like the interface to look like?  Are you just trying to namespace all the SDL functions and add constructors (fully imperative); are you trying to make a full fluent interface (everything is done by method chaining); are you trying to do something in between; or, is your goal something else entirely? 

My gut feeling is that you are trying to implement the same thing that I am, but with different syntax.  In order to test this theory, would you be willing to transcribe a small, yet full SDL program into your envisioned SDL++?  It can be something simple like this: [project](https://github.com/Twinklebear/TwinklebearDev-Lessons/blob/master/Lesson1/src/main.cpp).  It just creates a window and renderer, displays a picture, and shuts everything down.

Thanks for your help!

**Comment by DDunda** [comment]
Hi again, sorry for the long delay. Uni has been getting busy recently.

Ideally, my design for SDL++ is a thin wrapper for SDL. I wish for the functionality to be identical, while only adding low-cost abstractions that significantly benefit the programmer. For example, Windows, Renderers, and Textures are already 'objects' in SDL, so it makes sense to make them into _actual_ objects in SDL++. It's a similar logic as for why the SDL_ prefix on _everything_ was instead replaced with a namespace.

With this design in mind I'm now considering a replacement to if checking as quite unneeded. It is easier to write if statements than lambdas or try-catch blocks, their capabilities are much more broad, and if I'm honest they are extremely clear. Most importantly, ifs can actually change control flow and they run in the scope of the program. Considering this, I don't see a large advantage for the programmer in replacing ifs.

Though the current error-checking system is not yet fully implemented yet I would prefer to keep it. I intend for objects to have some sort of error variable to track if an error has occurred, as the Renderer does. This is done with a `|=` with internal function return values so you can just do `if(obj.error)` to detect an error. To my knowledge a bitwise or is one instruction, and does not restrict the capabilities of SDL++ compared to SDL. It may seem restrictive to blend multiple errors into one variable, but the SDL alternative is not seeing return values at all unless you check everything individually.

As for the transcription, here is a snippet of the important parts:
```c++
if (Init(SDL_INIT_VIDEO)) return 1;

Window win("Hello World!", {100, 100, 640, 480}, SDL_WINDOW_SHOWN);
if (win.error) return 1;

Renderer ren(win, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
if (ren.error) {
	Quit();
	return 1;
}

Surface bmp = IMG::Load("hello.bmp");
if (bmp.error) {
	Quit();
	return 1;
}

Texture tex(ren, bmp);
if (tex.error) {
	Quit();
	return 1;
}

for (int i = 0; i < 3; ++i) {
	ren.Clear();
	tex.Copy_Fill();
	ren.Present();
	Delay(1000);
}

Quit();
return 0;
```

Thank you for your patience, hopefully this is clear enough!

**Comment by repr-man** [comment]
Okay, that makes sense.  Thank you for the clarification and for your correspondence on this issue!
